openapi: 3.0.1
info:
  title: SNOMED CT Plugin
  description: A plugin that allows chatGPT to access SNOMED CT content. If the user asks for SNOMED CT codes, use the API to retrieve codes by searching for the concept term with the 'term' and 'language' query parameters and choosing the first match. Always send the 'language' query parameter with the request with the language code for the term. For example, 'en' for English. If there are no matches try again with the stem of the term.
  version: "v1"
servers:
  - url: https://sct-aiplugin.vercel.app/api
paths:
  /search:
    get:
      operationId: searchSnomedCT
      summary: Search by term
      parameters:
      - in: query
        name: term
        schema:
          type: string
          required: true
        description: The term used as filter to apply to the search results
      - in: query
        name: language
        schema:
          type: string
          required: true
        description: The language of the user prompt. Examples es, en, fr. Required value in all requests.
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/searchSnomedCTResponse'
components:
  schemas:
    searchSnomedCTResponse:
      type: object
      properties:
        expansion:
          type: object
          properties:
            contains:
              type: array
              items:
                type: object
                properties:
                  code:
                    type: string
                    description: The SNOMED CT code that matches the term.
